### ISSUE TITLE
Can't zget filenames with spaces

### ISSUE THREAD

**Issue by tristianc** [nils-werner/zget#2]
If I attempt the following between two different machines (Mac OS X 10.9, Fedora 21):

(OS X) zput "Some/ text.txt"
(Fedora) zget "Some/ text.txt"

Then, on OS X, I receive the following output:
Invalid request received. Aborting.
Done.

This is because of this line in put.py, I think:

```python
        if self.path == os.path.join('/', filename):
```

self.path contains: //Some%20text.txt
filename contains: //Some text.txt

**Comment by nils-werner** [comment]
Yup, didn't catch that one. It's been fixed in ddabea and uploaded to PyPI already. Use `pip install --upgrade zget` to upgrade.

**Comment by nils-werner** [comment]
Aaaand that's what you get for not testing your code properly :-) I've issued another release fixing issues with Python 3.
