### ISSUE TITLE
Sending file with absolute path fails

### ISSUE THREAD

**Issue by tristianc** [nils-werner/zget#3]
If I attempt the following between two different machines (Mac OS X 10.9, Fedora 21):

(OS X) zput "/Users/tristiancelestin/Desktop/some file.txt"
(Fedora) zget "/Users/tristiancelestin/Desktop/some file.txt" "some file.txt"

Then, on OS X, I receive the following output:
Invalid request received. Aborting.
Done.

This is because
self.path:  "//Users/tristiancelestin/Desktop/some%20file.txt"
filename: "/Users/tristiancelestin/Desktop/some%20file.txt"

**Comment by nils-werner** [comment]
OK, first of all I believe `zput` should only use the basename for peer resolution. Baiscally

   zput "/Users/tristiancelestin/Desktop/some file.txt"
   zget "some file.txt"

should work.

I'll see if I can come up with a fix that enables that.

**Comment by nils-werner** [comment]
1d3a969405985934561569d23dd5088f47e2c725 implements this.
